### ISSUE TITLE
Cauldron Custom Commands

### ISSUE THREAD

**Issue by tn5421** [Angush/dragon#1]
For some reason, Cauldron's custom commands are accessible via dragon on any server you invite it to.  I get the impression that server-based custom commands are only supposed to be usable on said server.  If you guys could look into this or tell me if I'm wrong that would be awesome.  
~ tn5421#0271

**Comment by Angush** [comment]
Dragon doesn't currently have a way to denote that specific commands should only be usable on specific servers, so it's working as intended. Thanks for submitting.
